name: easymvp-dev

services:
  easymvp-core:
    container_name: easymvp-core-dev
    image: easymvp-core:dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.core
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./docker/dev/config.yaml:/app/manifest/config/config.yaml:ro
      - easymvp_core_var:/app/var
    tmpfs:
      - /tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  easymvp_core_var:
