// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// acceptanceProfilesDao is the data access object for the table acceptance_profiles.
// You can define custom methods on it to extend its functionality as needed.
type acceptanceProfilesDao struct {
	*internal.AcceptanceProfilesDao
}

var (
	// AcceptanceProfiles is a globally accessible object for table acceptance_profiles operations.
	AcceptanceProfiles = acceptanceProfilesDao{internal.NewAcceptanceProfilesDao()}
)

// Add your custom methods and functionality below.
