// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// acceptanceJudgementsDao is the data access object for the table acceptance_judgements.
// You can define custom methods on it to extend its functionality as needed.
type acceptanceJudgementsDao struct {
	*internal.AcceptanceJudgementsDao
}

var (
	// AcceptanceJudgements is a globally accessible object for table acceptance_judgements operations.
	AcceptanceJudgements = acceptanceJudgementsDao{internal.NewAcceptanceJudgementsDao()}
)

// Add your custom methods and functionality below.
