// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// acceptanceRunsDao is the data access object for the table acceptance_runs.
// You can define custom methods on it to extend its functionality as needed.
type acceptanceRunsDao struct {
	*internal.AcceptanceRunsDao
}

var (
	// AcceptanceRuns is a globally accessible object for table acceptance_runs operations.
	AcceptanceRuns = acceptanceRunsDao{internal.NewAcceptanceRunsDao()}
)

// Add your custom methods and functionality below.
