// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// acceptanceSurfaceCoverageDao is the data access object for the table acceptance_surface_coverage.
// You can define custom methods on it to extend its functionality as needed.
type acceptanceSurfaceCoverageDao struct {
	*internal.AcceptanceSurfaceCoverageDao
}

var (
	// AcceptanceSurfaceCoverage is a globally accessible object for table acceptance_surface_coverage operations.
	AcceptanceSurfaceCoverage = acceptanceSurfaceCoverageDao{internal.NewAcceptanceSurfaceCoverageDao()}
)

// Add your custom methods and functionality below.
