// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// acceptanceIssuesDao is the data access object for the table acceptance_issues.
// You can define custom methods on it to extend its functionality as needed.
type acceptanceIssuesDao struct {
	*internal.AcceptanceIssuesDao
}

var (
	// AcceptanceIssues is a globally accessible object for table acceptance_issues operations.
	AcceptanceIssues = acceptanceIssuesDao{internal.NewAcceptanceIssuesDao()}
)

// Add your custom methods and functionality below.
