// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// acceptanceJourneyCoverageDao is the data access object for the table acceptance_journey_coverage.
// You can define custom methods on it to extend its functionality as needed.
type acceptanceJourneyCoverageDao struct {
	*internal.AcceptanceJourneyCoverageDao
}

var (
	// AcceptanceJourneyCoverage is a globally accessible object for table acceptance_journey_coverage operations.
	AcceptanceJourneyCoverage = acceptanceJourneyCoverageDao{internal.NewAcceptanceJourneyCoverageDao()}
)

// Add your custom methods and functionality below.
