// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// auditLogsDao is the data access object for the table audit_logs.
// You can define custom methods on it to extend its functionality as needed.
type auditLogsDao struct {
	*internal.AuditLogsDao
}

var (
	// AuditLogs is a globally accessible object for table audit_logs operations.
	AuditLogs = auditLogsDao{internal.NewAuditLogsDao()}
)

// Add your custom methods and functionality below.
