// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// brainRunBindingsDao is the data access object for the table brain_run_bindings.
// You can define custom methods on it to extend its functionality as needed.
type brainRunBindingsDao struct {
	*internal.BrainRunBindingsDao
}

var (
	// BrainRunBindings is a globally accessible object for table brain_run_bindings operations.
	BrainRunBindings = brainRunBindingsDao{internal.NewBrainRunBindingsDao()}
)

// Add your custom methods and functionality below.
