// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// completionVerdictsDao is the data access object for the table completion_verdicts.
// You can define custom methods on it to extend its functionality as needed.
type completionVerdictsDao struct {
	*internal.CompletionVerdictsDao
}

var (
	// CompletionVerdicts is a globally accessible object for table completion_verdicts operations.
	CompletionVerdicts = completionVerdictsDao{internal.NewCompletionVerdictsDao()}
)

// Add your custom methods and functionality below.
