// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// conversationsDao is the data access object for the table conversations.
type conversationsDao struct {
	*internal.ConversationsDao
}

var (
	// Conversations is a globally accessible object for table conversations operations.
	Conversations = conversationsDao{internal.NewConversationsDao()}
)

// Add your custom methods and functionality below.
