// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// diagnosticRecordsDao is the data access object for the table diagnostic_records.
// You can define custom methods on it to extend its functionality as needed.
type diagnosticRecordsDao struct {
	*internal.DiagnosticRecordsDao
}

var (
	// DiagnosticRecords is a globally accessible object for table diagnostic_records operations.
	DiagnosticRecords = diagnosticRecordsDao{internal.NewDiagnosticRecordsDao()}
)

// Add your custom methods and functionality below.
