// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// domainTasksDao is the data access object for the table domain_tasks.
// You can define custom methods on it to extend its functionality as needed.
type domainTasksDao struct {
	*internal.DomainTasksDao
}

var (
	// DomainTasks is a globally accessible object for table domain_tasks operations.
	DomainTasks = domainTasksDao{internal.NewDomainTasksDao()}
)

// Add your custom methods and functionality below.
