// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// evidenceItemsDao is the data access object for the table evidence_items.
// You can define custom methods on it to extend its functionality as needed.
type evidenceItemsDao struct {
	*internal.EvidenceItemsDao
}

var (
	// EvidenceItems is a globally accessible object for table evidence_items operations.
	EvidenceItems = evidenceItemsDao{internal.NewEvidenceItemsDao()}
)

// Add your custom methods and functionality below.
