// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// evidenceLinksDao is the data access object for the table evidence_links.
// You can define custom methods on it to extend its functionality as needed.
type evidenceLinksDao struct {
	*internal.EvidenceLinksDao
}

var (
	// EvidenceLinks is a globally accessible object for table evidence_links operations.
	EvidenceLinks = evidenceLinksDao{internal.NewEvidenceLinksDao()}
)

// Add your custom methods and functionality below.
