// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// messagesDao is the data access object for the table messages.
type messagesDao struct {
	*internal.MessagesDao
}

var (
	// Messages is a globally accessible object for table messages operations.
	Messages = messagesDao{internal.NewMessagesDao()}
)

// Add your custom methods and functionality below.
