// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// productionAcceptanceProfilesDao is the data access object for the table production_acceptance_profiles.
// You can define custom methods on it to extend its functionality as needed.
type productionAcceptanceProfilesDao struct {
	*internal.ProductionAcceptanceProfilesDao
}

var (
	// ProductionAcceptanceProfiles is a globally accessible object for table production_acceptance_profiles operations.
	ProductionAcceptanceProfiles = productionAcceptanceProfilesDao{internal.NewProductionAcceptanceProfilesDao()}
)

// Add your custom methods and functionality below.
