// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// projectsDao is the data access object for the table projects.
// You can define custom methods on it to extend its functionality as needed.
type projectsDao struct {
	*internal.ProjectsDao
}

var (
	// Projects is a globally accessible object for table projects operations.
	Projects = projectsDao{internal.NewProjectsDao()}
)

// Add your custom methods and functionality below.
