// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// projectSnapshotsDao is the data access object for the table project_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type projectSnapshotsDao struct {
	*internal.ProjectSnapshotsDao
}

var (
	// ProjectSnapshots is a globally accessible object for table project_snapshots operations.
	ProjectSnapshots = projectSnapshotsDao{internal.NewProjectSnapshotsDao()}
)

// Add your custom methods and functionality below.
