// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// projectProfilesDao is the data access object for the table project_profiles.
// You can define custom methods on it to extend its functionality as needed.
type projectProfilesDao struct {
	*internal.ProjectProfilesDao
}

var (
	// ProjectProfiles is a globally accessible object for table project_profiles operations.
	ProjectProfiles = projectProfilesDao{internal.NewProjectProfilesDao()}
)

// Add your custom methods and functionality below.
