// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// projectWorkspacesDao is the data access object for the table project_workspaces.
// You can define custom methods on it to extend its functionality as needed.
type projectWorkspacesDao struct {
	*internal.ProjectWorkspacesDao
}

var (
	// ProjectWorkspaces is a globally accessible object for table project_workspaces operations.
	ProjectWorkspaces = projectWorkspacesDao{internal.NewProjectWorkspacesDao()}
)

// Add your custom methods and functionality below.
