// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// replayItemsDao is the data access object for the table replay_items.
// You can define custom methods on it to extend its functionality as needed.
type replayItemsDao struct {
	*internal.ReplayItemsDao
}

var (
	// ReplayItems is a globally accessible object for table replay_items operations.
	ReplayItems = replayItemsDao{internal.NewReplayItemsDao()}
)

// Add your custom methods and functionality below.
