// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// requirementsDao is the data access object for the table requirements.
// You can define custom methods on it to extend its functionality as needed.
type requirementsDao struct {
	*internal.RequirementsDao
}

var (
	// Requirements is a globally accessible object for table requirements operations.
	Requirements = requirementsDao{internal.NewRequirementsDao()}
)

// Add your custom methods and functionality below.
