// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// runCheckpointsDao is the data access object for the table run_checkpoints.
// You can define custom methods on it to extend its functionality as needed.
type runCheckpointsDao struct {
	*internal.RunCheckpointsDao
}

var (
	// RunCheckpoints is a globally accessible object for table run_checkpoints operations.
	RunCheckpoints = runCheckpointsDao{internal.NewRunCheckpointsDao()}
)

// Add your custom methods and functionality below.
