// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// runEventIndexDao is the data access object for the table run_event_index.
// You can define custom methods on it to extend its functionality as needed.
type runEventIndexDao struct {
	*internal.RunEventIndexDao
}

var (
	// RunEventIndex is a globally accessible object for table run_event_index operations.
	RunEventIndex = runEventIndexDao{internal.NewRunEventIndexDao()}
)

// Add your custom methods and functionality below.
