// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// taskManualGatesDao is the data access object for the table task_manual_gates.
// You can define custom methods on it to extend its functionality as needed.
type taskManualGatesDao struct {
	*internal.TaskManualGatesDao
}

var (
	// TaskManualGates is a globally accessible object for table task_manual_gates operations.
	TaskManualGates = taskManualGatesDao{internal.NewTaskManualGatesDao()}
)

// Add your custom methods and functionality below.
