// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// taskDependenciesDao is the data access object for the table task_dependencies.
// You can define custom methods on it to extend its functionality as needed.
type taskDependenciesDao struct {
	*internal.TaskDependenciesDao
}

var (
	// TaskDependencies is a globally accessible object for table task_dependencies operations.
	TaskDependencies = taskDependenciesDao{internal.NewTaskDependenciesDao()}
)

// Add your custom methods and functionality below.
