// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// workflowCompiledTasksDao is the data access object for the table workflow_compiled_tasks.
// You can define custom methods on it to extend its functionality as needed.
type workflowCompiledTasksDao struct {
	*internal.WorkflowCompiledTasksDao
}

var (
	// WorkflowCompiledTasks is a globally accessible object for table workflow_compiled_tasks operations.
	WorkflowCompiledTasks = workflowCompiledTasksDao{internal.NewWorkflowCompiledTasksDao()}
)

// Add your custom methods and functionality below.
