// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// workspaceSnapshotsDao is the data access object for the table workspace_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type workspaceSnapshotsDao struct {
	*internal.WorkspaceSnapshotsDao
}

var (
	// WorkspaceSnapshots is a globally accessible object for table workspace_snapshots operations.
	WorkspaceSnapshots = workspaceSnapshotsDao{internal.NewWorkspaceSnapshotsDao()}
)

// Add your custom methods and functionality below.
