// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// workflowPlanDraftsDao is the data access object for the table workflow_plan_drafts.
// You can define custom methods on it to extend its functionality as needed.
type workflowPlanDraftsDao struct {
	*internal.WorkflowPlanDraftsDao
}

var (
	// WorkflowPlanDrafts is a globally accessible object for table workflow_plan_drafts operations.
	WorkflowPlanDrafts = workflowPlanDraftsDao{internal.NewWorkflowPlanDraftsDao()}
)

// Add your custom methods and functionality below.
