// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/leef-l/easymvp/apps/core/internal/dao/internal"
)

// workflowCompiledPlansDao is the data access object for the table workflow_compiled_plans.
// You can define custom methods on it to extend its functionality as needed.
type workflowCompiledPlansDao struct {
	*internal.WorkflowCompiledPlansDao
}

var (
	// WorkflowCompiledPlans is a globally accessible object for table workflow_compiled_plans operations.
	WorkflowCompiledPlans = workflowCompiledPlansDao{internal.NewWorkflowCompiledPlansDao()}
)

// Add your custom methods and functionality below.
