CREATE TABLE IF NOT EXISTS `mvp_quality_finding` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '雪花ID',
  `workflow_run_id` BIGINT UNSIGNED NOT NULL COMMENT '所属工作流运行ID',
  `stage_code` VARCHAR(32) NOT NULL COMMENT '阶段: review/accept/rework',
  `producer` VARCHAR(32) NOT NULL COMMENT '发现者: hard_rule/llm_judge/experience_reviewer/human',
  `severity` VARCHAR(16) NOT NULL COMMENT '严重级别: blocker/error/warn/info',
  `rule_code` VARCHAR(64) NOT NULL COMMENT '规则代码或llm_auto',
  `target_type` VARCHAR(32) NOT NULL COMMENT '目标类型: task/file/blueprint/project',
  `target_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '目标ID',
  `message` TEXT NOT NULL COMMENT '问题描述',
  `evidence_json` JSON DEFAULT NULL COMMENT '证据JSON',
  `resolved` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已解决',
  `resolved_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '解决人ID',
  `resolved_at` DATETIME DEFAULT NULL COMMENT '解决时间',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `dept_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '部门ID',
  `created_at` DATETIME NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_finding` (`workflow_run_id`, `stage_code`, `rule_code`, `target_type`, `target_id`),
  KEY `idx_workflow_severity` (`workflow_run_id`, `severity`),
  KEY `idx_datascope` (`dept_id`, `created_by`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='统一质量发现';
