// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/ai/internal/dao/internal"
)

// aiModelDao is the data access object for the table ai_model.
// You can define custom methods on it to extend its functionality as needed.
type aiModelDao struct {
	*internal.AiModelDao
}

var (
	// AiModel is a globally accessible object for table ai_model operations.
	AiModel = aiModelDao{internal.NewAiModelDao()}
)

// Add your custom methods and functionality below.
