// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/ai/internal/dao/internal"
)

// aiPlanDao is the data access object for the table ai_plan.
// You can define custom methods on it to extend its functionality as needed.
type aiPlanDao struct {
	*internal.AiPlanDao
}

var (
	// AiPlan is a globally accessible object for table ai_plan operations.
	AiPlan = aiPlanDao{internal.NewAiPlanDao()}
)

// Add your custom methods and functionality below.
