// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/ai/internal/dao/internal"
)

// aiProviderDao is the data access object for the table ai_provider.
// You can define custom methods on it to extend its functionality as needed.
type aiProviderDao struct {
	*internal.AiProviderDao
}

var (
	// AiProvider is a globally accessible object for table ai_provider operations.
	AiProvider = aiProviderDao{internal.NewAiProviderDao()}
)

// Add your custom methods and functionality below.
