// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpTaskResourceLockDao is the data access object for the table mvp_task_resource_lock.
// You can define custom methods on it to extend its functionality as needed.
type mvpTaskResourceLockDao struct {
	*internal.MvpTaskResourceLockDao
}

var (
	// MvpTaskResourceLock is a globally accessible object for table mvp_task_resource_lock operations.
	MvpTaskResourceLock = mvpTaskResourceLockDao{internal.NewMvpTaskResourceLockDao()}
)

// Add your custom methods and functionality below.
