// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpRolePresetDao is the data access object for the table mvp_role_preset.
// You can define custom methods on it to extend its functionality as needed.
type mvpRolePresetDao struct {
	*internal.MvpRolePresetDao
}

var (
	// MvpRolePreset is a globally accessible object for table mvp_role_preset operations.
	MvpRolePreset = mvpRolePresetDao{internal.NewMvpRolePresetDao()}
)

// Add your custom methods and functionality below.
