// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpConfigDao is the data access object for the table mvp_config.
// You can define custom methods on it to extend its functionality as needed.
type mvpConfigDao struct {
	*internal.MvpConfigDao
}

var (
	// MvpConfig is a globally accessible object for table mvp_config operations.
	MvpConfig = mvpConfigDao{internal.NewMvpConfigDao()}
)

// Add your custom methods and functionality below.
