// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpWorkflowRunDao is the data access object for the table mvp_workflow_run.
// You can define custom methods on it to extend its functionality as needed.
type mvpWorkflowRunDao struct {
	*internal.MvpWorkflowRunDao
}

var (
	// MvpWorkflowRun is a globally accessible object for table mvp_workflow_run operations.
	MvpWorkflowRun = mvpWorkflowRunDao{internal.NewMvpWorkflowRunDao()}
)

// Add your custom methods and functionality below.
