// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpProjectDao is the data access object for the table mvp_project.
// You can define custom methods on it to extend its functionality as needed.
type mvpProjectDao struct {
	*internal.MvpProjectDao
}

var (
	// MvpProject is a globally accessible object for table mvp_project operations.
	MvpProject = mvpProjectDao{internal.NewMvpProjectDao()}
)

// Add your custom methods and functionality below.
