// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpAcceptEvidenceDao is the data access object for the table mvp_accept_evidence.
// You can define custom methods on it to extend its functionality as needed.
type mvpAcceptEvidenceDao struct {
	*internal.MvpAcceptEvidenceDao
}

var (
	// MvpAcceptEvidence is a globally accessible object for table mvp_accept_evidence operations.
	MvpAcceptEvidence = mvpAcceptEvidenceDao{internal.NewMvpAcceptEvidenceDao()}
)

// Add your custom methods and functionality below.
