// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpAcceptRuleDao is the data access object for the table mvp_accept_rule.
// You can define custom methods on it to extend its functionality as needed.
type mvpAcceptRuleDao struct {
	*internal.MvpAcceptRuleDao
}

var (
	// MvpAcceptRule is a globally accessible object for table mvp_accept_rule operations.
	MvpAcceptRule = mvpAcceptRuleDao{internal.NewMvpAcceptRuleDao()}
)

// Add your custom methods and functionality below.
