// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpConversationDao is the data access object for the table mvp_conversation.
// You can define custom methods on it to extend its functionality as needed.
type mvpConversationDao struct {
	*internal.MvpConversationDao
}

var (
	// MvpConversation is a globally accessible object for table mvp_conversation operations.
	MvpConversation = mvpConversationDao{internal.NewMvpConversationDao()}
)

// Add your custom methods and functionality below.
