// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpWorkflowEventDao is the data access object for the table mvp_workflow_event.
// You can define custom methods on it to extend its functionality as needed.
type mvpWorkflowEventDao struct {
	*internal.MvpWorkflowEventDao
}

var (
	// MvpWorkflowEvent is a globally accessible object for table mvp_workflow_event operations.
	MvpWorkflowEvent = mvpWorkflowEventDao{internal.NewMvpWorkflowEventDao()}
)

// Add your custom methods and functionality below.
