// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpAcceptIssueDao is the data access object for the table mvp_accept_issue.
// You can define custom methods on it to extend its functionality as needed.
type mvpAcceptIssueDao struct {
	*internal.MvpAcceptIssueDao
}

var (
	// MvpAcceptIssue is a globally accessible object for table mvp_accept_issue operations.
	MvpAcceptIssue = mvpAcceptIssueDao{internal.NewMvpAcceptIssueDao()}
)

// Add your custom methods and functionality below.
