// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpStageTaskDao is the data access object for the table mvp_stage_task.
// You can define custom methods on it to extend its functionality as needed.
type mvpStageTaskDao struct {
	*internal.MvpStageTaskDao
}

var (
	// MvpStageTask is a globally accessible object for table mvp_stage_task operations.
	MvpStageTask = mvpStageTaskDao{internal.NewMvpStageTaskDao()}
)

// Add your custom methods and functionality below.
