// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpMessageDao is the data access object for the table mvp_message.
// You can define custom methods on it to extend its functionality as needed.
type mvpMessageDao struct {
	*internal.MvpMessageDao
}

var (
	// MvpMessage is a globally accessible object for table mvp_message operations.
	MvpMessage = mvpMessageDao{internal.NewMvpMessageDao()}
)

// Add your custom methods and functionality below.
