// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpTaskBlueprintDao is the data access object for the table mvp_task_blueprint.
// You can define custom methods on it to extend its functionality as needed.
type mvpTaskBlueprintDao struct {
	*internal.MvpTaskBlueprintDao
}

var (
	// MvpTaskBlueprint is a globally accessible object for table mvp_task_blueprint operations.
	MvpTaskBlueprint = mvpTaskBlueprintDao{internal.NewMvpTaskBlueprintDao()}
)

// Add your custom methods and functionality below.
