// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpProjectRoleDao is the data access object for the table mvp_project_role.
// You can define custom methods on it to extend its functionality as needed.
type mvpProjectRoleDao struct {
	*internal.MvpProjectRoleDao
}

var (
	// MvpProjectRole is a globally accessible object for table mvp_project_role operations.
	MvpProjectRole = mvpProjectRoleDao{internal.NewMvpProjectRoleDao()}
)

// Add your custom methods and functionality below.
