// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpStageRunDao is the data access object for the table mvp_stage_run.
// You can define custom methods on it to extend its functionality as needed.
type mvpStageRunDao struct {
	*internal.MvpStageRunDao
}

var (
	// MvpStageRun is a globally accessible object for table mvp_stage_run operations.
	MvpStageRun = mvpStageRunDao{internal.NewMvpStageRunDao()}
)

// Add your custom methods and functionality below.
