// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpHandoffRecordDao is the data access object for the table mvp_handoff_record.
// You can define custom methods on it to extend its functionality as needed.
type mvpHandoffRecordDao struct {
	*internal.MvpHandoffRecordDao
}

var (
	// MvpHandoffRecord is a globally accessible object for table mvp_handoff_record operations.
	MvpHandoffRecord = mvpHandoffRecordDao{internal.NewMvpHandoffRecordDao()}
)

// Add your custom methods and functionality below.
