// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpDomainTaskDao is the data access object for the table mvp_domain_task.
// You can define custom methods on it to extend its functionality as needed.
type mvpDomainTaskDao struct {
	*internal.MvpDomainTaskDao
}

var (
	// MvpDomainTask is a globally accessible object for table mvp_domain_task operations.
	MvpDomainTask = mvpDomainTaskDao{internal.NewMvpDomainTaskDao()}
)

// Add your custom methods and functionality below.
