// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpTaskDao is the data access object for the table mvp_task.
// You can define custom methods on it to extend its functionality as needed.
type mvpTaskDao struct {
	*internal.MvpTaskDao
}

var (
	// MvpTask is a globally accessible object for table mvp_task operations.
	MvpTask = mvpTaskDao{internal.NewMvpTaskDao()}
)

// Add your custom methods and functionality below.
