// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpAcceptRunDao is the data access object for the table mvp_accept_run.
// You can define custom methods on it to extend its functionality as needed.
type mvpAcceptRunDao struct {
	*internal.MvpAcceptRunDao
}

var (
	// MvpAcceptRun is a globally accessible object for table mvp_accept_run operations.
	MvpAcceptRun = mvpAcceptRunDao{internal.NewMvpAcceptRunDao()}
)

// Add your custom methods and functionality below.
