// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpProjectCategoryDao is the data access object for the table mvp_project_category.
// You can define custom methods on it to extend its functionality as needed.
type mvpProjectCategoryDao struct {
	*internal.MvpProjectCategoryDao
}

var (
	// MvpProjectCategory is a globally accessible object for table mvp_project_category operations.
	MvpProjectCategory = mvpProjectCategoryDao{internal.NewMvpProjectCategoryDao()}
)

// Add your custom methods and functionality below.
