// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpReviewIssueDao is the data access object for the table mvp_review_issue.
// You can define custom methods on it to extend its functionality as needed.
type mvpReviewIssueDao struct {
	*internal.MvpReviewIssueDao
}

var (
	// MvpReviewIssue is a globally accessible object for table mvp_review_issue operations.
	MvpReviewIssue = mvpReviewIssueDao{internal.NewMvpReviewIssueDao()}
)

// Add your custom methods and functionality below.
