// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpPlanVersionDao is the data access object for the table mvp_plan_version.
// You can define custom methods on it to extend its functionality as needed.
type mvpPlanVersionDao struct {
	*internal.MvpPlanVersionDao
}

var (
	// MvpPlanVersion is a globally accessible object for table mvp_plan_version operations.
	MvpPlanVersion = mvpPlanVersionDao{internal.NewMvpPlanVersionDao()}
)

// Add your custom methods and functionality below.
