// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpTaskLogDao is the data access object for the table mvp_task_log.
// You can define custom methods on it to extend its functionality as needed.
type mvpTaskLogDao struct {
	*internal.MvpTaskLogDao
}

var (
	// MvpTaskLog is a globally accessible object for table mvp_task_log operations.
	MvpTaskLog = mvpTaskLogDao{internal.NewMvpTaskLogDao()}
)

// Add your custom methods and functionality below.
