// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"easymvp/app/mvp/internal/dao/internal"
)

// mvpTaskWorkspaceDao is the data access object for the table mvp_task_workspace.
// You can define custom methods on it to extend its functionality as needed.
type mvpTaskWorkspaceDao struct {
	*internal.MvpTaskWorkspaceDao
}

var (
	// MvpTaskWorkspace is a globally accessible object for table mvp_task_workspace operations.
	MvpTaskWorkspace = mvpTaskWorkspaceDao{internal.NewMvpTaskWorkspaceDao()}
)

// Add your custom methods and functionality below.
