
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  run:
    path: "."
    extra: ""
    watchPaths:
      - "internal"
      - "api"

  gen:
    dao:
      - link: "mysql:easymvp:JKcHFJYXnkrB6BXE@tcp(127.0.0.1:3306)/easymvp?charset=utf8mb4"
        tables: "ai_engine,ai_engine_config,ai_model,ai_plan,ai_provider,ai_task,ai_task_log"
        descriptionTag: true
        noJsonTag: true
        noModelComment: false
        overwriteDao: false

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
