# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":9001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  path:              "/www/wwwroot/project/easymvp/admin-go/logs/ai"
  level:             "all"
  stdout:            false
  rotateSize:        "100M"
  rotateExpire:      "7d"
  rotateBackupLimit: 10
  stStatus:          0

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:easymvp:JKcHFJYXnkrB6BXE@tcp(127.0.0.1:3306)/easymvp"
    debug: false
    charset: "utf8mb4"

# JWT 配置
jwt:
  secret: "easymvp-secret-key-2026"
  expire: 24  # Token 过期时间（小时）
