
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  run:
    path: "main.go"
    extra: ""
    watchPaths:
      - "internal"
      - "api"

  gen:
    dao:
      - link: "mysql:easymvp:JKcHFJYXnkrB6BXE@tcp(127.0.0.1:3306)/easymvp?charset=utf8mb4"
        tables: "mvp_accept_evidence,mvp_accept_issue,mvp_accept_rule,mvp_accept_run,mvp_config,mvp_conversation,mvp_domain_task,mvp_handoff_record,mvp_message,mvp_plan_version,mvp_project,mvp_project_category,mvp_project_role,mvp_review_issue,mvp_role_preset,mvp_stage_run,mvp_stage_task,mvp_task,mvp_task_blueprint,mvp_task_log,mvp_task_resource_lock,mvp_task_workspace,mvp_workflow_event,mvp_workflow_run"
        descriptionTag: true
        noJsonTag: true
        noModelComment: false
        overwriteDao: false

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
